#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Dec 21, 2017 07:51:12 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import analyger_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = My_Analyser (root)
    analyger_support.init(root, top)
    root.mainloop()

w = None
def create_My_Analyser(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = My_Analyser (w)
    analyger_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_My_Analyser():
    global w
    w.destroy()
    w = None


class My_Analyser:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {DejaVu Sans} -size 13 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("915x684+761+365")
        top.title("My Analyser")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.61, rely=0.48, height=26, width=67)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(text='''Analyse''')
        self.Button1.configure(width=67)

        self.Label_min = Label(top)
        self.Label_min.place(relx=0.08, rely=0.07, height=23, width=32)
        self.Label_min.configure(text='''Min''')

        self.Label_max = Label(top)
        self.Label_max.place(relx=0.15, rely=0.07, height=18, width=55)
        self.Label_max.configure(activebackground="#f9f9f9")
        self.Label_max.configure(text='''Max''')
        self.Label_max.configure(width=55)

        self.Entry_min = Entry(top)
        self.Entry_min.place(relx=0.07, rely=0.13, relheight=0.03, relwidth=0.07)

        self.Entry_min.configure(background="white")
        self.Entry_min.configure(font="TkFixedFont")
        self.Entry_min.configure(width=66)

        self.Entry_max = Entry(top)
        self.Entry_max.place(relx=0.15, rely=0.13, relheight=0.03, relwidth=0.07)

        self.Entry_max.configure(background="white")
        self.Entry_max.configure(font="TkFixedFont")
        self.Entry_max.configure(width=66)

        self.Button_array_gen = Button(top)
        self.Button_array_gen.place(relx=0.05, rely=0.23, height=26, width=167)
        self.Button_array_gen.configure(activebackground="#d9d9d9")
        self.Button_array_gen.configure(text='''Generate Array''')
        self.Button_array_gen.configure(width=167)

        self.bubble_sort = Label(top)
        self.bubble_sort.place(relx=0.36, rely=0.12, height=18, width=106)
        self.bubble_sort.configure(text='''Bubble Sort :''')
        self.bubble_sort.configure(width=106)

        self.Entry_bubble_sort_result = Entry(top)
        self.Entry_bubble_sort_result.place(relx=0.48, rely=0.12, relheight=0.03
                , relwidth=0.18)
        self.Entry_bubble_sort_result.configure(background="white")
        self.Entry_bubble_sort_result.configure(font="TkFixedFont")
        self.Entry_bubble_sort_result.configure(selectbackground="#c4c4c4")
        self.Entry_bubble_sort_result.configure(width=166)

        self.insertion_sort = Label(top)
        self.insertion_sort.place(relx=0.34, rely=0.16, height=18, width=126)
        self.insertion_sort.configure(activebackground="#f9f9f9")
        self.insertion_sort.configure(text='''Insertion Sort :''')
        self.insertion_sort.configure(width=126)

        self.Entry_insertion_sort_result1 = Entry(top)
        self.Entry_insertion_sort_result1.place(relx=0.48, rely=0.16
                , relheight=0.03, relwidth=0.18)
        self.Entry_insertion_sort_result1.configure(background="white")
        self.Entry_insertion_sort_result1.configure(font="TkFixedFont")
        self.Entry_insertion_sort_result1.configure(selectbackground="#c4c4c4")
        self.Entry_insertion_sort_result1.configure(width=166)

        self.selection_sort = Label(top)
        self.selection_sort.place(relx=0.33, rely=0.2, height=18, width=140)
        self.selection_sort.configure(text='''Selection Sort :''')
        self.selection_sort.configure(width=140)

        self.Entry_selection_sort_result = Entry(top)
        self.Entry_selection_sort_result.place(relx=0.48, rely=0.2
                , relheight=0.03, relwidth=0.18)
        self.Entry_selection_sort_result.configure(background="white")
        self.Entry_selection_sort_result.configure(font="TkFixedFont")
        self.Entry_selection_sort_result.configure(width=166)

        self.merge_sort = Label(top)
        self.merge_sort.place(relx=0.35, rely=0.25, height=18, width=116)
        self.merge_sort.configure(text='''Merge Sort :''')
        self.merge_sort.configure(width=116)

        self.Entry_merge_sort_result = Entry(top)
        self.Entry_merge_sort_result.place(relx=0.48, rely=0.25, relheight=0.03
                , relwidth=0.18)
        self.Entry_merge_sort_result.configure(background="white")
        self.Entry_merge_sort_result.configure(font="TkFixedFont")
        self.Entry_merge_sort_result.configure(width=166)

        self.heap_sort = Label(top)
        self.heap_sort.place(relx=0.36, rely=0.29, height=23, width=109)
        self.heap_sort.configure(text='''Heap Sort :''')
        self.heap_sort.configure(width=109)

        self.Entry_heap_sort_result = Entry(top)
        self.Entry_heap_sort_result.place(relx=0.48, rely=0.29, relheight=0.03
                , relwidth=0.18)
        self.Entry_heap_sort_result.configure(background="white")
        self.Entry_heap_sort_result.configure(font="TkFixedFont")
        self.Entry_heap_sort_result.configure(width=166)

        self.Label8 = Label(top)
        self.Label8.place(relx=0.36, rely=0.34, height=23, width=112)
        self.Label8.configure(text='''Quick Sort :''')
        self.Label8.configure(width=112)

        self.Entry_quick_sort_result = Entry(top)
        self.Entry_quick_sort_result.place(relx=0.48, rely=0.34, relheight=0.03
                , relwidth=0.18)
        self.Entry_quick_sort_result.configure(background="white")
        self.Entry_quick_sort_result.configure(font="TkFixedFont")
        self.Entry_quick_sort_result.configure(width=166)

        self.counting_sort = Label(top)
        self.counting_sort.place(relx=0.34, rely=0.38, height=23, width=128)
        self.counting_sort.configure(text='''Counting Sort :''')
        self.counting_sort.configure(width=128)

        self.Entry_counting_sort_result = Entry(top)
        self.Entry_counting_sort_result.place(relx=0.48, rely=0.38
                , relheight=0.03, relwidth=0.18)
        self.Entry_counting_sort_result.configure(background="white")
        self.Entry_counting_sort_result.configure(font="TkFixedFont")
        self.Entry_counting_sort_result.configure(width=166)

        self.radix_sort = Label(top)
        self.radix_sort.place(relx=0.36, rely=0.42, height=23, width=111)
        self.radix_sort.configure(text='''Radix Sort :''')
        self.radix_sort.configure(width=111)

        self.Entry_radix_sort_result = Entry(top)
        self.Entry_radix_sort_result.place(relx=0.48, rely=0.42, relheight=0.03
                , relwidth=0.18)
        self.Entry_radix_sort_result.configure(background="white")
        self.Entry_radix_sort_result.configure(font="TkFixedFont")
        self.Entry_radix_sort_result.configure(width=166)

        self.algos = Label(top)
        self.algos.place(relx=0.33, rely=0.06, height=24, width=109)
        self.algos.configure(font=font10)
        self.algos.configure(highlightcolor="#b40000")
        self.algos.configure(text='''Algorithms''')
        self.algos.configure(width=109)

        self.time = Label(top)
        self.time.place(relx=0.45, rely=0.06, height=24, width=109)
        self.time.configure(activebackground="#f9f9f9")
        self.time.configure(font=font10)
        self.time.configure(highlightcolor="#b40000")
        self.time.configure(text='''Time''')

        self.algos1 = Label(top)
        self.algos1.place(relx=0.43, rely=0.6, height=24, width=159)
        self.algos1.configure(activebackground="#f9f9f9")
        self.algos1.configure(font=font10)
        self.algos1.configure(highlightcolor="#b40000")
        self.algos1.configure(text='''Unsorted Array''')
        self.algos1.configure(width=159)

        self.unsoterd_array_result = Label(top)
        self.unsoterd_array_result.place(relx=0.02, rely=0.66, height=48
                , width=905)
        self.unsoterd_array_result.configure(text='''N/A''')
        self.unsoterd_array_result.configure(width=905)

        self.algos2 = Label(top)
        self.algos2.place(relx=0.45, rely=0.76, height=24, width=129)
        self.algos2.configure(activebackground="#f9f9f9")
        self.algos2.configure(font=font10)
        self.algos2.configure(highlightcolor="#b40000")
        self.algos2.configure(text='''Sorted Array''')
        self.algos2.configure(width=129)

        self.sorted_array_result = Label(top)
        self.sorted_array_result.place(relx=0.02, rely=0.83, height=58
                , width=906)
        self.sorted_array_result.configure(text='''N/A''')
        self.sorted_array_result.configure(width=906)

        self.Button_plot = Button(top)
        self.Button_plot.place(relx=0.74, rely=0.48, height=26, width=197)
        self.Button_plot.configure(activebackground="#d9d9d9")
        self.Button_plot.configure(text='''Plot Graph''')
        self.Button_plot.configure(width=197)






if __name__ == '__main__':
    vp_start_gui()



